Feat/selection input icon change
eduardconstantin/azure-cloud-exams pull request #128
Opened 2024-10-07 17:20 UTC by Dhruvnotfound

Fixes #127  

- [ ] I have read and agree to the [Code of Conduct](https://github.com/eduardconstantin/azure-fundamentals/blob/main/CODE_OF_CONDUCT.md), and have followed the [Contributing guidelines](https://github.com/eduardconstantin/azure-fundamentals/blob/main/CONTRIBUTING.md).

## Pull Request Type

- [ ] Other

## Summary
before- showing cross(x) as we select an option

after- showing circle as we select an option
![image](https://github.com/user-attachments/assets/82f8f3f5-29db-4361-9577-dab289983f76)
Please review the PR! Thank you!

2024-10-07 18:44 UTC, eduardconstantin requested changes

2024-10-07 18:44 UTC, eduardconstantin commented on components/QuizExamForm.tsx
> +                          d="M 2 0 a 2 2 0 0 0 -2 2 v 12 a 2 2 0 0 0 2 2 h 12 a 2 2 0 0 0 2 -2 V 2 a 2 2 0 0 0 -2 -2 H 2 z z"
```suggestion
                          d="M 16 8 A 8 8 0 1 1 0 8 a 8 8 0 0 1 16 0 z z"
```

2024-10-07 18:44 UTC, eduardconstantin commented on components/SelectionInput.tsx
> +                  ? "M 2 0 a 2 2 0 0 0 -2 2 v 12 a 2 2 0 0 0 2 2 h 12 a 2 2 0 0 0 2 -2 V 2 a 2 2 0 0 0 -2 -2 H 2 z z"
```suggestion
                  ? "M 16 8 A 8 8 0 1 1 0 8 a 8 8 0 0 1 16 0 z z"
```

2024-10-07 18:44 UTC, eduardconstantin commented on components/SelectionInput.tsx
>                    : "M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm3.354 4.646L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646
```suggestion
                  : "M 2 0 a 2 2 0 0 0 -2 2 v 12 a 2 2 0 0 0 2 2 h 12 a 2 2 0 0 0 2 -2 V 2 a 2 2 0 0 0 -2 -2 H 2 z z"
```

2024-10-08 05:00 UTC, Dhruvnotfound commented
all the requested changes has been made 
thanks for checking the pr request

2024-10-08 08:49 UTC, danieldanielecki commented
love this solution!

2024-10-08 15:11 UTC, eduardconstantin commented
> love this solution!

I guess my idea with x marking the correct answer is not that intuitive :)

2024-10-08 15:12 UTC, eduardconstantin approved these changes
Perfect! Thank you!

2024-10-08 15:12 UTC, merged